#!/bin/bash

# This script is the entry point for the docker container.
# It will add the host machine's user to the dockern and then execute userentry.sh

if (grep -s -q "^$USER:" /etc/passwd); then
    echo "found $USER in docker container"
else
    echo "adding host machine user $USER ($UID) to docker container"
    grep -s -q ":$GID:" /etc/group || groupadd -g "$GID" "$GROUP"
    useradd -d /yocto -u "$UID" -g "$GID" "$USER"
    echo "$USER:$USER" | chpasswd
fi

export PATH=/yocto:${PATH}

if [ -z "$(which kas)" ]
then
    /yocto/installDevEnv.sh
fi

# preserve sanctioned env vars for all users within the docker instance
if [ $# -eq 0 ]
then
    exec sudo --user="${USER}" /bin/bash
else
    exec sudo --user="${USER}" "$@"
fi
